version: "3.6"

services:
  lyncex:
    build: .
    command: swipl main.pl
    volumes:
    - ./lyncex:/opt/lyncex
    ports:
    - 11011:11011
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    command: behave
    volumes:
    - ./lyncex:/opt/lyncex
    - ./features:/opt/lyncex/features
    depends_on:
    - lyncex
