version: "3.6"

services:
  lyncex:
    build: .
    command: swipl start.pl
    volumes:
    - ./lyncex:/opt/lyncex
    ports:
    - 11011:11011
    environment:
    - LYNCEX_RDF_SCHEMA_VALIDATION=true
  test-e2e:
    build:
      context: .
      dockerfile: Dockerfile.test
    command: behave
    volumes:
    - ./lyncex:/opt/lyncex
    - ./features:/opt/lyncex/features
    depends_on:
    - lyncex
  test-unit:
    build: .
    command: swipl -s main.pl -g run_tests,halt -t 'halt(1)'
    volumes:
    - ./lyncex:/opt/lyncex
