name: Test
on: [push]
jobs:
  test-e2e:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build Docker images
      run: docker-compose build
    - name: Execute E2E test
      run: docker-compose run test